<ul>
  <li>
    <p>Breakfast</p>
    <ul>
      <li>карточка</li>
      <li>карточка</li>
      <li>карточка</li>
      <li>карточка</li>
    </ul>
  </li>
  <li>
    <p>Chicken</p>
    <ul>
      <li>карточка</li>
      <li>карточка</li>
      <li>карточка</li>
      <li>карточка</li>
    </ul>
  </li>
</ul>;